### ISSUE TITLE
ValueError: setting an array element with a sequence

### ISSUE THREAD

**Issue by xw11111** [tbereau/auto_martini#42] opened 2023-11-01 18:28 UTC
I encountered an error when using the following command, and no output was generated. Does anybody know how to solve it? I really appreciate it!
python -m auto_martini --smi "CCCCCCCCCCOC1C(C(C(C(O1)CO)O)O)O" --mol GLU --cg glu.gro --top GLU.itp
![Screenshot from 2023-11-01 14-15-01](https://github.com/tbereau/auto_martini/assets/107816078/2deb9831-d495-4a06-b240-7f819469c140)

**Comment by yajairazepeda** [comment] 2024-01-22 23:16
Hi, have you figure out how to solve it? I have the same issue.

**Comment by tbereau** [comment] 2024-03-12 10:09
maybe try installing with `pip` instead of `poetry`

**Comment by anabiman** [comment] 2024-03-13 05:00
The problem is coming from cython. I have a quick fix for this.

**Closed** 2024-03-14 07:33 UTC
